spring:
  application:
    name: oauth2
    main:
      allow-bean-definition-overriding: true
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
    cloud:
      nacos:
        discovery:
          server-addr: 47.106.81.186:8848

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver  # 高版本用这个不然会有警告
    jdbc-url: jdbc:mysql://47.106.81.186:3306/template_oauth?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ENC(iLiAmvnHL2Zds1b8VtRzwK0177zcsTtPBeeWec4vML4BlDP+DR20vnQBhAYbH0/n)
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1


dubbo:
  scan:
    base-packages: com.xiayu.oauth.controller
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://47.106.81.186:8848
    provider:
      loadbalance: roundrobin  #负载均衡方式  轮循
      # random 随机，roundrobin 轮循，leastactive 最少活跃调用数，consistenthash一致性 Hash

# 外部配置
oauth2:
  grant_type: password
  client_id: client
  client_secret: secret
  url_oauth: http://localhost:9000/oauth/token

